cookbook 'apt', '~> 2.3.0'
cookbook 'apache2', '~> 1.8.14'
cookbook 'build-essential', '~> 1.4.2'
cookbook 'database', '~> 1.5.2'
cookbook 'git', '~> 2.8.4'
cookbook 'dmg', '~> 2.0.8'
cookbook 'mysql', '~> 4.0.10'
cookbook 'openssl', '~> 1.1.0'
cookbook 'php', '~> 1.2.6'
cookbook 'ssh_known_hosts', '~> 1.1.0'
cookbook 'sudo', '~> 2.2.2'
cookbook "drupal", git: "https://github.com/newmediadenver/drupal", tag: "v1.0.0"
